[app]
name = "maicraft-next"
version = "0.1.0"
debug = true
data_dir = "./data"

[logging]
level = "debug"
console = true
file = true
max_file_size = 10485760
max_files = 5
log_dir = "./logs"

[minecraft]
host = "localhost"
port = 25565
username = "MaicraftBot"
password = ""
auth = "offline"
reconnect = true
reconnect_delay = 5000
max_reconnect_attempts = 5
timeout = 30000
keep_alive = true

[agent]
model_name = "gpt-4"
max_tokens = 4096
temperature = 0.7
decision_timeout = 30000
max_actions_per_minute = 30
safe_mode = true
allow_destructive_actions = false
memory_limit = 1000
save_memory_interval = 60000

[plugins]
enabled = [ "armor-manager", "pathfinder", "collectblock", "pvp", "tool" ]

[plugins.armor-manager]
auto_equip = true
prefer_protection = true

[plugins.pathfinder]
timeout = 10000
search_radius = 100

[plugins.collectblock]
max_distance = 16
auto_collect = true

[plugins.pvp]
enabled = false
auto_attack = false

[plugins.tool]
auto_switch = true
prefer_efficiency = true

[advanced]
hot_reload = true
config_backup = true
backup_count = 5
tick_rate = 20
max_concurrent_tasks = 10
allow_operator_commands = false
restricted_items = []