# Maicraft Next 配置模板文件
# 复制此文件为 config.toml 并根据需要修改配置

[app]
# 应用基础配置
name = "maicraft-next"
version = "0.1.0"
debug = false
data_dir = "./data"

[logging]
# 日志配置
level = "info"  # error, warn, info, debug
console = true
file = true
max_file_size = 10485760  # 10MB
max_files = 5
log_dir = "./logs"

[minecraft]
# Minecraft 服务器连接配置
host = "localhost"
port = 25565
username = "MaicraftBot"
password = ""  # 留空为离线模式
auth = "offline"  # offline, mojang, microsoft

# 重连配置
reconnect = true
reconnect_delay = 5000  # 毫秒
max_reconnect_attempts = 5

# 网络配置
timeout = 30000  # 毫秒
keep_alive = true

[agent]
# AI 代理配置
model_name = "gpt-4"
max_tokens = 4096
temperature = 0.7
decision_timeout = 30000  # 毫秒

# 行为限制
max_actions_per_minute = 30
safe_mode = true
allow_destructive_actions = false

# 记忆配置
memory_limit = 1000  # 最大记忆条目数
save_memory_interval = 60000  # 毫秒

[plugins]
# 插件配置
enabled = [
  "armor-manager",
  "pathfinder",
  "collectblock",
  "pvp",
  "tool"
]

[plugins.armor-manager]
auto_equip = true
prefer_protection = true

[plugins.pathfinder]
timeout = 10000
search_radius = 100

[plugins.collectblock]
max_distance = 16
auto_collect = true

[plugins.pvp]
enabled = false
auto_attack = false

[plugins.tool]
auto_switch = true
prefer_efficiency = true

[advanced]
# 高级配置
hot_reload = true
config_backup = true
backup_count = 5

# 性能配置
tick_rate = 20  # 游戏刻率
max_concurrent_tasks = 10

# 安全配置
allow_operator_commands = false
restricted_items = []  # 禁用的物品ID列表